// import axios from "axios";

// export default async function UpdateItem(id, data) {
//   try {
//     const res = await axios({
//       method: "PATCH",
//       url: `https://salic.sharepoint.com/sites/MDM/_api/web/lists/getbytitle('KPIs 2022')/items(${id})`,
//       headers: {
//         "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IlVYRFZOMTMzUVpQNnk5aVBWdnJOX19waXJaZmlXdEcxLURJZFQzVjN4QnMiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9iZWExYjQxNy00MjM3LTQwYjgtYjAyMC01N2ZjZTlhYmRiNDMvIiwiaWF0IjoxNjczMzYwMjI0LCJuYmYiOjE2NzMzNjAyMjQsImV4cCI6MTY3MzM2NDEyNCwiYWlvIjoiRTJaZ1lIanAvK0JVdHQ2MGhKZ1B5KzdsZlB0c0JnQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJTYWxpY0NvbnNvbGUiLCJhcHBpZCI6Ijg5OTNiMDQ4LWRlNzEtNGZlZC05OGI4LTZkYWUyYzZkNzUwMyIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2JlYTFiNDE3LTQyMzctNDBiOC1iMDIwLTU3ZmNlOWFiZGI0My8iLCJpZHR5cCI6ImFwcCIsIm9pZCI6ImUzMmQzNGMzLTEzZTQtNDYyZi04MGNlLTEwYzMyODM2YWNhOSIsInJoIjoiMC5BVWdBRjdTaHZqZEN1RUN3SUZmODZhdmJRd01BQUFBQUFBQUF3QUFBQUFBQUFBQklBQUEuIiwicm9sZXMiOlsiQ2hhdC5VcGRhdGVQb2xpY3lWaW9sYXRpb24uQWxsIiwiQ2FsbHMuSm9pbkdyb3VwQ2FsbC5BbGwiLCJFZHVSb3N0ZXIuUmVhZC5BbGwiLCJPbmxpbmVNZWV0aW5ncy5SZWFkLkFsbCIsIk1haWwuUmVhZFdyaXRlIiwiT25saW5lTWVldGluZ3MuUmVhZFdyaXRlLkFsbCIsIkRldmljZS5SZWFkV3JpdGUuQWxsIiwiVXNlci5SZWFkV3JpdGUuQWxsIiwiRG9tYWluLlJlYWRXcml0ZS5BbGwiLCJBcHBsaWNhdGlvbi5SZWFkV3JpdGUuT3duZWRCeSIsIlNlY3VyaXR5RXZlbnRzLlJlYWQuQWxsIiwiQ2FsZW5kYXJzLlJlYWQiLCJFZHVBc3NpZ25tZW50cy5SZWFkV3JpdGUuQWxsIiwiUGVvcGxlLlJlYWQuQWxsIiwiQXBwbGljYXRpb24uUmVhZFdyaXRlLkFsbCIsIkNhbGxzLkluaXRpYXRlR3JvdXBDYWxsLkFsbCIsIkdyb3VwLlJlYWQuQWxsIiwiQWNjZXNzUmV2aWV3LlJlYWRXcml0ZS5BbGwiLCJEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCIsIkVkdUFzc2lnbm1lbnRzLlJlYWRXcml0ZUJhc2ljLkFsbCIsIk1haWxib3hTZXR0aW5ncy5SZWFkIiwiRWR1QWRtaW5pc3RyYXRpb24uUmVhZC5BbGwiLCJDYWxscy5Kb2luR3JvdXBDYWxsQXNHdWVzdC5BbGwiLCJTaXRlcy5SZWFkLkFsbCIsIlNpdGVzLlJlYWRXcml0ZS5BbGwiLCJDb250YWN0cy5SZWFkV3JpdGUiLCJHcm91cC5SZWFkV3JpdGUuQWxsIiwiU2l0ZXMuTWFuYWdlLkFsbCIsIlNlY3VyaXR5RXZlbnRzLlJlYWRXcml0ZS5BbGwiLCJOb3Rlcy5SZWFkLkFsbCIsIlVzZXIuSW52aXRlLkFsbCIsIkVkdVJvc3Rlci5SZWFkV3JpdGUuQWxsIiwiRmlsZXMuUmVhZFdyaXRlLkFsbCIsIkRpcmVjdG9yeS5SZWFkLkFsbCIsIlVzZXIuUmVhZC5BbGwiLCJFZHVBc3NpZ25tZW50cy5SZWFkQmFzaWMuQWxsIiwiRWR1Um9zdGVyLlJlYWRCYXNpYy5BbGwiLCJGaWxlcy5SZWFkLkFsbCIsIk1haWwuUmVhZCIsIkNoYXQuUmVhZC5BbGwiLCJDaGFubmVsTWVzc2FnZS5SZWFkLkFsbCIsIlVzZXIuRXhwb3J0LkFsbCIsIkVkdUFzc2lnbm1lbnRzLlJlYWQuQWxsIiwiQ2FsZW5kYXJzLlJlYWRXcml0ZSIsIklkZW50aXR5Umlza3lVc2VyLlJlYWQuQWxsIiwiQWNjZXNzUmV2aWV3LlJlYWQuQWxsIiwiRWR1QWRtaW5pc3RyYXRpb24uUmVhZFdyaXRlLkFsbCIsIk1haWwuU2VuZCIsIkNoYW5uZWxNZXNzYWdlLlVwZGF0ZVBvbGljeVZpb2xhdGlvbi5BbGwiLCJNYWlsYm94U2V0dGluZ3MuUmVhZFdyaXRlIiwiQ29udGFjdHMuUmVhZCIsIklkZW50aXR5Umlza0V2ZW50LlJlYWQuQWxsIiwiQXVkaXRMb2cuUmVhZC5BbGwiLCJNZW1iZXIuUmVhZC5IaWRkZW4iLCJDYWxscy5BY2Nlc3NNZWRpYS5BbGwiLCJQcm9ncmFtQ29udHJvbC5SZWFkLkFsbCIsIlNpdGVzLkZ1bGxDb250cm9sLkFsbCIsIlByb2dyYW1Db250cm9sLlJlYWRXcml0ZS5BbGwiLCJSZXBvcnRzLlJlYWQuQWxsIiwiQ2FsbHMuSW5pdGlhdGUuQWxsIiwiTm90ZXMuUmVhZFdyaXRlLkFsbCJdLCJzdWIiOiJlMzJkMzRjMy0xM2U0LTQ2MmYtODBjZS0xMGMzMjgzNmFjYTkiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiJiZWExYjQxNy00MjM3LTQwYjgtYjAyMC01N2ZjZTlhYmRiNDMiLCJ1dGkiOiIyM0RlNkpqOW9FYUYxbXZLUEh3VkFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyI5MzYwZmViNS1mNDE4LTRiYWEtODE3NS1lMmEwMGJhYzQzMDEiLCI4OGQ4ZTNlMy04ZjU1LTRhMWUtOTUzYS05Yjk4OThiODg3NmIiLCIyYjQ5OWJjZC1kYTQ0LTQ5NjgtOGFlYy03OGUxNjc0ZmE2NGQiLCIwOTk3YTFkMC0wZDFkLTRhY2ItYjQwOC1kNWNhNzMxMjFlOTAiXSwieG1zX3RjZHQiOjE0MzE4NTQwNzR9.D5RmXu81qvjE33LgMsd5cxURkADaiKBxxgElGAJpBBuiZppJ03riEh1SnEkXWoha1-y_1vohsJyZefXarrL1liSeMcfI3eJTWNVV6M6pyFrUBODBi8lowMeeDo_wOeBC2Vkq8SJQMBPvqzZst3dAcNaCYkdUe7fSHzTeWMNkCNfDGtWUg-RGEvhfXrxRU6kixAh2TY_pwGt_MxJ2OkXlwj57OqM3FYTNqxD0Y7dzsfs-c1l-5Ll2y3d23XpTnediziUn42eQoOH6ByeG7YO3MY1SFlA1wxnY85C-gLUbsQkYRgjpXcu9hUWtcWUw0yAHPQ0mr7arzBZ-SF73A27oIA",
//         "Accept": "application/json;odata=verbose",
//         "Content-Type": "application/json;odata=verbose",
//         "X-HTTP-Method": "MERGE",
//         "IF-MATCH": "*"
//       },
//       body: JSON.stringify(data)
//     });

//     return res;
//   } catch (err) {
//     console.log(err);
//     return err;
//   }
// }










import pnp from "sp-pnp-js";

export default async function UpdateItem(id, data) {
  try {
    const res = await pnp.sp.web.lists
      .getByTitle("Corporate Objective KPIs 2022")
      .items.getById(id)
      .update(data);
    return res;
  } catch (err) {
    console.log(err);
    return err;
  }
}