import { Select } from 'antd'
import React from 'react'

function NationaltiesOptions() {
  return (
    <>
      <Select.Option value="afghan">Afghan</Select.Option>
      <Select.Option value="albanian">Albanian</Select.Option>
      <Select.Option value="algerian">Algerian</Select.Option>
      <Select.Option value="american">American</Select.Option>
      <Select.Option value="andorran">Andorran</Select.Option>
      <Select.Option value="angolan">Angolan</Select.Option>
      <Select.Option value="antiguans">Antiguans</Select.Option>
      <Select.Option value="argentinean">Argentinean</Select.Option>
      <Select.Option value="armenian">Armenian</Select.Option>
      <Select.Option value="australian">Australian</Select.Option>
      <Select.Option value="austrian">Austrian</Select.Option>
      <Select.Option value="azerbaijani">Azerbaijani</Select.Option>
      <Select.Option value="bahamian">Bahamian</Select.Option>
      <Select.Option value="bahraini">Bahraini</Select.Option>
      <Select.Option value="bangladeshi">Bangladeshi</Select.Option>
      <Select.Option value="barbadian">Barbadian</Select.Option>
      <Select.Option value="barbudans">Barbudans</Select.Option>
      <Select.Option value="batswana">Batswana</Select.Option>
      <Select.Option value="belarusian">Belarusian</Select.Option>
      <Select.Option value="belgian">Belgian</Select.Option>
      <Select.Option value="belizean">Belizean</Select.Option>
      <Select.Option value="beninese">Beninese</Select.Option>
      <Select.Option value="bhutanese">Bhutanese</Select.Option>
      <Select.Option value="bolivian">Bolivian</Select.Option>
      <Select.Option value="bosnian">Bosnian</Select.Option>
      <Select.Option value="brazilian">Brazilian</Select.Option>
      <Select.Option value="british">British</Select.Option>
      <Select.Option value="bruneian">Bruneian</Select.Option>
      <Select.Option value="bulgarian">Bulgarian</Select.Option>
      <Select.Option value="burkinabe">Burkinabe</Select.Option>
      <Select.Option value="burmese">Burmese</Select.Option>
      <Select.Option value="burundian">Burundian</Select.Option>
      <Select.Option value="cambodian">Cambodian</Select.Option>
      <Select.Option value="cameroonian">Cameroonian</Select.Option>
      <Select.Option value="canadian">Canadian</Select.Option>
      <Select.Option value="cape verdean">Cape Verdean</Select.Option>
      <Select.Option value="central african">Central African</Select.Option>
      <Select.Option value="chadian">Chadian</Select.Option>
      <Select.Option value="chilean">Chilean</Select.Option>
      <Select.Option value="chinese">Chinese</Select.Option>
      <Select.Option value="colombian">Colombian</Select.Option>
      <Select.Option value="comoran">Comoran</Select.Option>
      <Select.Option value="congolese">Congolese</Select.Option>
      <Select.Option value="costa rican">Costa Rican</Select.Option>
      <Select.Option value="croatian">Croatian</Select.Option>
      <Select.Option value="cuban">Cuban</Select.Option>
      <Select.Option value="cypriot">Cypriot</Select.Option>
      <Select.Option value="czech">Czech</Select.Option>
      <Select.Option value="danish">Danish</Select.Option>
      <Select.Option value="djibouti">Djibouti</Select.Option>
      <Select.Option value="dominican">Dominican</Select.Option>
      <Select.Option value="dutch">Dutch</Select.Option>
      <Select.Option value="east timorese">East Timorese</Select.Option>
      <Select.Option value="ecuadorean">Ecuadorean</Select.Option>
      <Select.Option value="egyptian">Egyptian</Select.Option>
      <Select.Option value="emirian">Emirian</Select.Option>
      <Select.Option value="equatorial guinean">Equatorial Guinean</Select.Option>
      <Select.Option value="eritrean">Eritrean</Select.Option>
      <Select.Option value="estonian">Estonian</Select.Option>
      <Select.Option value="ethiopian">Ethiopian</Select.Option>
      <Select.Option value="fijian">Fijian</Select.Option>
      <Select.Option value="filipino">Filipino</Select.Option>
      <Select.Option value="finnish">Finnish</Select.Option>
      <Select.Option value="french">French</Select.Option>
      <Select.Option value="gabonese">Gabonese</Select.Option>
      <Select.Option value="gambian">Gambian</Select.Option>
      <Select.Option value="georgian">Georgian</Select.Option>
      <Select.Option value="german">German</Select.Option>
      <Select.Option value="ghanaian">Ghanaian</Select.Option>
      <Select.Option value="greek">Greek</Select.Option>
      <Select.Option value="grenadian">Grenadian</Select.Option>
      <Select.Option value="guatemalan">Guatemalan</Select.Option>
      <Select.Option value="guinea-bissauan">Guinea-Bissauan</Select.Option>
      <Select.Option value="guinean">Guinean</Select.Option>
      <Select.Option value="guyanese">Guyanese</Select.Option>
      <Select.Option value="haitian">Haitian</Select.Option>
      <Select.Option value="herzegovinian">Herzegovinian</Select.Option>
      <Select.Option value="honduran">Honduran</Select.Option>
      <Select.Option value="hungarian">Hungarian</Select.Option>
      <Select.Option value="icelander">Icelander</Select.Option>
      <Select.Option value="indian">Indian</Select.Option>
      <Select.Option value="indonesian">Indonesian</Select.Option>
      <Select.Option value="iranian">Iranian</Select.Option>
      <Select.Option value="iraqi">Iraqi</Select.Option>
      <Select.Option value="irish">Irish</Select.Option>
      <Select.Option value="israeli">Israeli</Select.Option>
      <Select.Option value="italian">Italian</Select.Option>
      <Select.Option value="ivorian">Ivorian</Select.Option>
      <Select.Option value="jamaican">Jamaican</Select.Option>
      <Select.Option value="japanese">Japanese</Select.Option>
      <Select.Option value="jordanian">Jordanian</Select.Option>
      <Select.Option value="kazakhstani">Kazakhstani</Select.Option>
      <Select.Option value="kenyan">Kenyan</Select.Option>
      <Select.Option value="kittian and nevisian">Kittian and Nevisian</Select.Option>
      <Select.Option value="kuwaiti">Kuwaiti</Select.Option>
      <Select.Option value="kyrgyz">Kyrgyz</Select.Option>
      <Select.Option value="laotian">Laotian</Select.Option>
      <Select.Option value="latvian">Latvian</Select.Option>
      <Select.Option value="lebanese">Lebanese</Select.Option>
      <Select.Option value="liberian">Liberian</Select.Option>
      <Select.Option value="libyan">Libyan</Select.Option>
      <Select.Option value="liechtensteiner">Liechtensteiner</Select.Option>
      <Select.Option value="lithuanian">Lithuanian</Select.Option>
      <Select.Option value="luxembourger">Luxembourger</Select.Option>
      <Select.Option value="macedonian">Macedonian</Select.Option>
      <Select.Option value="malagasy">Malagasy</Select.Option>
      <Select.Option value="malawian">Malawian</Select.Option>
      <Select.Option value="malaysian">Malaysian</Select.Option>
      <Select.Option value="maldivan">Maldivan</Select.Option>
      <Select.Option value="malian">Malian</Select.Option>
      <Select.Option value="maltese">Maltese</Select.Option>
      <Select.Option value="marshallese">Marshallese</Select.Option>
      <Select.Option value="mauritanian">Mauritanian</Select.Option>
      <Select.Option value="mauritian">Mauritian</Select.Option>
      <Select.Option value="mexican">Mexican</Select.Option>
      <Select.Option value="micronesian">Micronesian</Select.Option>
      <Select.Option value="moldovan">Moldovan</Select.Option>
      <Select.Option value="monacan">Monacan</Select.Option>
      <Select.Option value="mongolian">Mongolian</Select.Option>
      <Select.Option value="moroccan">Moroccan</Select.Option>
      <Select.Option value="mosotho">Mosotho</Select.Option>
      <Select.Option value="motswana">Motswana</Select.Option>
      <Select.Option value="mozambican">Mozambican</Select.Option>
      <Select.Option value="namibian">Namibian</Select.Option>
      <Select.Option value="nauruan">Nauruan</Select.Option>
      <Select.Option value="nepalese">Nepalese</Select.Option>
      <Select.Option value="new zealander">New Zealander</Select.Option>
      <Select.Option value="ni-vanuatu">Ni-Vanuatu</Select.Option>
      <Select.Option value="nicaraguan">Nicaraguan</Select.Option>
      <Select.Option value="nigerien">Nigerien</Select.Option>
      <Select.Option value="north korean">North Korean</Select.Option>
      <Select.Option value="northern irish">Northern Irish</Select.Option>
      <Select.Option value="norwegian">Norwegian</Select.Option>
      <Select.Option value="omani">Omani</Select.Option>
      <Select.Option value="palestinian">Palestinian</Select.Option>
      <Select.Option value="pakistani">Pakistani</Select.Option>
      <Select.Option value="palauan">Palauan</Select.Option>
      <Select.Option value="panamanian">Panamanian</Select.Option>
      <Select.Option value="papua new guinean">Papua New Guinean</Select.Option>
      <Select.Option value="paraguayan">Paraguayan</Select.Option>
      <Select.Option value="peruvian">Peruvian</Select.Option>
      <Select.Option value="polish">Polish</Select.Option>
      <Select.Option value="portuguese">Portuguese</Select.Option>
      <Select.Option value="qatari">Qatari</Select.Option>
      <Select.Option value="romanian">Romanian</Select.Option>
      <Select.Option value="russian">Russian</Select.Option>
      <Select.Option value="rwandan">Rwandan</Select.Option>
      <Select.Option value="saint lucian">Saint Lucian</Select.Option>
      <Select.Option value="salvadoran">Salvadoran</Select.Option>
      <Select.Option value="samoan">Samoan</Select.Option>
      <Select.Option value="san marinese">San Marinese</Select.Option>
      <Select.Option value="sao tomean">Sao Tomean</Select.Option>
      <Select.Option value="saudi">Saudi</Select.Option>
      <Select.Option value="scottish">Scottish</Select.Option>
      <Select.Option value="senegalese">Senegalese</Select.Option>
      <Select.Option value="serbian">Serbian</Select.Option>
      <Select.Option value="seychellois">Seychellois</Select.Option>
      <Select.Option value="sierra leonean">Sierra Leonean</Select.Option>
      <Select.Option value="singaporean">Singaporean</Select.Option>
      <Select.Option value="slovakian">Slovakian</Select.Option>
      <Select.Option value="slovenian">Slovenian</Select.Option>
      <Select.Option value="solomon islander">Solomon Islander</Select.Option>
      <Select.Option value="somali">Somali</Select.Option>
      <Select.Option value="south african">South African</Select.Option>
      <Select.Option value="south korean">South Korean</Select.Option>
      <Select.Option value="spanish">Spanish</Select.Option>
      <Select.Option value="sri lankan">Sri Lankan</Select.Option>
      <Select.Option value="sudanese">Sudanese</Select.Option>
      <Select.Option value="surinamer">Surinamer</Select.Option>
      <Select.Option value="swazi">Swazi</Select.Option>
      <Select.Option value="swedish">Swedish</Select.Option>
      <Select.Option value="swiss">Swiss</Select.Option>
      <Select.Option value="syrian">Syrian</Select.Option>
      <Select.Option value="taiwanese">Taiwanese</Select.Option>
      <Select.Option value="tajik">Tajik</Select.Option>
      <Select.Option value="tanzanian">Tanzanian</Select.Option>
      <Select.Option value="thai">Thai</Select.Option>
      <Select.Option value="togolese">Togolese</Select.Option>
      <Select.Option value="tongan">Tongan</Select.Option>
      <Select.Option value="trinidadian or tobagonian">Trinidadian or Tobagonian</Select.Option>
      <Select.Option value="tunisian">Tunisian</Select.Option>
      <Select.Option value="turkish">Turkish</Select.Option>
      <Select.Option value="tuvaluan">Tuvaluan</Select.Option>
      <Select.Option value="ugandan">Ugandan</Select.Option>
      <Select.Option value="ukrainian">Ukrainian</Select.Option>
      <Select.Option value="uruguayan">Uruguayan</Select.Option>
      <Select.Option value="uzbekistani">Uzbekistani</Select.Option>
      <Select.Option value="venezuelan">Venezuelan</Select.Option>
      <Select.Option value="vietnamese">Vietnamese</Select.Option>
      <Select.Option value="welsh">Welsh</Select.Option>
      <Select.Option value="yemenite">Yemenite</Select.Option>
      <Select.Option value="zambian">Zambian</Select.Option>
      <Select.Option value="zimbabwean">Zimbabwean</Select.Option>
    </>
  )
}

export default NationaltiesOptions